# Generated by Django 3.0.7 on 2020-11-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
