# Generated by Django 3.0.7 on 2020-11-16 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20201116_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
