# Generated by Django 3.0.7 on 2020-11-17 05:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_pair_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pair',
            name='price',
            field=models.FloatField(max_length=32, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='pair',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
